package com.samcod3.meditrack.domain.model

/**
 * Structured content block detected by AI from leaflet HTML.
 * Represents different formatting elements in the document.
 */
sealed class ContentBlock {
    /** Normal paragraph text */
    data class Paragraph(val text: String) : ContentBlock()
    
    /** Bold/emphasized text */
    data class Bold(val text: String) : ContentBlock()
    
    /** Italic text */
    data class Italic(val text: String) : ContentBlock()
    
    /** Bullet list item (unordered) */
    data class BulletItem(val text: String) : ContentBlock()
    
    /** Numbered list item (ordered) */
    data class NumberedItem(val number: Int, val text: String) : ContentBlock()
    
    /** Sub-heading within a section */
    data class SubHeading(val text: String) : ContentBlock()
}

/**
 * A section detected dynamically from the leaflet.
 * The number of sections is not fixed - AI detects all that exist.
 */
data class ParsedSection(
    val title: String,
    val content: List<ContentBlock>,
    val rawHtml: String = ""  // Original HTML for WebView rendering
)

/**
 * Structured summary of the leaflet generated by AI.
 */
data class LeafletSummary(
    val indications: String,
    val dosage: String,
    val warnings: String
)

/**
 * Complete parsed leaflet with all detected sections.
 */
data class ParsedLeaflet(
    val sections: List<ParsedSection>,
    val summary: LeafletSummary? = null
) {
    companion object {
        val EMPTY = ParsedLeaflet(emptyList())
    }
}
